'$schema' = "https://awslabs.github.io/duvet/config/v0.4.0.json"

[[source]]
pattern = "local-php-sdk/src/S3/**/*.php"

[[source]]
pattern = "local-php-sdk/src/Crypto/**/*.php"

[[source]]
pattern = "local-php-sdk/tests/S3/**/*.php"

[[source]]
pattern = "local-php-sdk/tests/Crypto/**/*.php"

[[source]]
pattern = "compliance_exceptions/*.txt"

# Include required specifications here
[[specification]]
source = "../specification/s3-encryption/data-format/content-metadata.md"
[[specification]]
source = "../specification/s3-encryption/data-format/metadata-strategy.md"
[[specification]]
source = "../specification/s3-encryption/client.md"
[[specification]]
source = "../specification/s3-encryption/decryption.md"
[[specification]]
source = "../specification/s3-encryption/encryption.md"
[[specification]]
source = "../specification/s3-encryption/key-derivation.md"
[[specification]]
source = "../specification/s3-encryption/key-commitment.md"

[report.html]
enabled = true

# Enable snapshots to prevent requirement coverage regressions
[report.snapshot]
enabled = false
