source 'https://rubygems.org'

ruby '~> 3.0'

gem 'sinatra', '~> 3.0'
gem 'puma', '~> 6.0'
gem 'aws-sdk-s3', path: 'local-ruby-sdk/gems/aws-sdk-s3'
gem 'aws-sdk-kms', path: 'local-ruby-sdk/gems/aws-sdk-kms'
gem 'json', '~> 2.0'
gem 'concurrent-ruby', '~> 1.0'
gem 'nokogiri', '~> 1.13'

group :development do
  gem 'rubocop', '~> 1.0'
end
