<?php

require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/client.php';
require_once __DIR__ . '/get_object.php';
require_once __DIR__ . '/put_object.php';

use Aws\S3\Crypto\S3EncryptionClientV2;
use Aws\Crypto\KmsMaterialsProviderV2;
use Aws\S3\S3Client;
use Aws\Kms\KmsClient;

use Ramsey\Uuid\Uuid;
use GuzzleHttp\Psr7\Response;

// Function to read session ID from cookies.txt file
function getSessionIdFromCookiesFile()
{
    $cookiesFile = __DIR__ . '/../cookies.txt';

    if (!file_exists($cookiesFile)) {
        return null;
    }

    $lines = file($cookiesFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

    foreach ($lines as $line) {
        // Skip comment lines
        if (strpos($line, '#') === 0) {
            continue;
        }

        // Parse cookie line: domain, flag, path, secure, expiration, name, value
        $parts = explode("\t", $line);
        if (count($parts) >= 7 && $parts[5] === 'PHPSESSID') {
            return $parts[6]; // Return the session ID value
        }
    }

    error_log("No session Id found");

    return null;
}

// Function to write session ID to cookies.txt file
function writeSessionIdToCookiesFile($sessionId)
{
    $cookiesFile = __DIR__ . '/../cookies.txt';

    // Create Netscape cookie format entry
    $cookieLine = "localhost\tFALSE\t/\tFALSE\t0\tPHPSESSID\t$sessionId";

    // Write header and cookie entry
    $content = "# Netscape HTTP Cookie File\n";
    $content .= "# https://curl.se/docs/http-cookies.html\n";
    $content .= "# This file was generated by libcurl! Edit at your own risk.\n\n";
    $content .= $cookieLine . "\n";

    file_put_contents($cookiesFile, $content);
}

// Start session to persist cache across requests
// First try to use session ID from cookies.txt if available
$sessionId = getSessionIdFromCookiesFile();
if ($sessionId) {
    session_id($sessionId);
}
session_start();

// Initialize session cache if it doesn't exist
if (!isset($_SESSION['s3ecCache'])) {
    $_SESSION['s3ecCache'] = [];
}

// Simple router class
class SimpleRouter
{
    private $routes = [];

    public function addRoute($method, $path, $handler)
    {
        $this->routes[] = [
            'method' => strtoupper($method),
            'path' => $path,
            'handler' => $handler
        ];
    }

    public function handleRequest()
    {
        $method = $_SERVER['REQUEST_METHOD'];
        $path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);

        foreach ($this->routes as $route) {
            if ($route['method'] === $method) {
                $params = $this->matchPathWithParams($route['path'], $path);
                if ($params !== false) {
                    return call_user_func($route['handler'], $params);
                }
            }
        }

        // Default 404 response
        http_response_code(404);
        return json_encode(['error' => 'Not Found']);
    }

    private function matchPathWithParams($routePath, $requestPath)
    {
        // Handle exact matches first (for routes without parameters)
        if ($routePath === $requestPath) {
            return [];
        }

        // Convert route path like '/object/{bucket}/{key}' to regex
        $pattern = preg_replace('/\{([^}]+)\}/', '([^/]+)', $routePath);
        $pattern = '/^' . str_replace('/', '\/', $pattern) . '$/';

        if (preg_match($pattern, $requestPath, $matches)) {
            array_shift($matches); // Remove full match

            // Extract parameter names
            preg_match_all('/\{([^}]+)\}/', $routePath, $paramNames);
            $params = [];

            foreach ($paramNames[1] as $index => $paramName) {
                $params[$paramName] = $matches[$index] ?? null;
            }

            return $params;
        }

        return false;
    }
}

// Helper function to get cached client by ID
function getCachedClient($clientId)
{
    if (!isset($_SESSION['s3ecCache'][$clientId])) {
        return null;
    }

    $config = $_SESSION['s3ecCache'][$clientId];

    // Recreate the AWS clients from stored configuration
    $s3Client = new S3Client($config['s3Config']);
    $encryptionClient = new S3EncryptionClientV2($s3Client);

    $kmsClient = new KmsClient($config['kmsConfig']);
    $materialsProvider = new KmsMaterialsProviderV2($kmsClient, $config['kmsKeyId']);

    return [
        'encryptionClient' => $encryptionClient,
        'materialsProvider' => $materialsProvider,
        'config' => $config
    ];
}

function createDefaultClientTuple(): array
{
    $s3Client = new S3Client([
        'region' => 'us-west-2',
        'version' => 'latest',
        'http' => [
            'debug' => false,
            'verify' => true,
            'curl' => [
                CURLOPT_VERBOSE => false,
                CURLOPT_NOPROGRESS => true
            ]
        ]
    ]);
    $encryptionClient = new S3EncryptionClientV2($s3Client);

    $kmsClient = new KmsClient([
        'region' => 'us-west-2',
        'version' => 'latest',
        'http' => [
            'debug' => false,
            'verify' => true,
            'curl' => [
                CURLOPT_VERBOSE => false,
                CURLOPT_NOPROGRESS => true
            ]
        ]
    ]);
    $materialsProvider = new KmsMaterialsProviderV2($kmsClient, 'arn:aws:kms:us-west-2:370957321024:alias/S3EC-Test-Server-Github-KMS-Key');

    return [
        'encryptionClient' => $encryptionClient,
        'materialsProvider' => $materialsProvider
    ];
}

function metadataStringToMap($metadata): array
{
    $md = [];

    if (empty($metadata)) {
        return $md;
    }

    $mdList = explode(',', $metadata);

    foreach ($mdList as $entry) {
        $parts = explode(']:[', $entry);

        if (count($parts) === 2) {
            $key = substr($parts[0], 1);
            $value = substr($parts[1], 0, -1);
            $md[$key] = $value;
        } else {
            throw new InvalidArgumentException("Malformed metadata list entry: " . $entry);
        }
    }

    return $md;
}
function formatMetadataForResponse($metadata)
{
    $metadataList = [];
    // Handle different metadata input types
    if (is_array($metadata)) {
        // If it's an associative array (like Python dict)
        foreach ($metadata as $key => $value) {
            $metadataList[] = $key . '=' . $value;
        }
    } elseif (is_string($metadata) && !empty($metadata)) {
        // If it's already a string, assume it's in the correct format
        return $metadata;
    }

    // Convert array to comma-separated string
    return implode(',', $metadataList);
}

// Initialize router
$router = new SimpleRouter();

// Add basic routes
$router->addRoute('GET', '/', function () {
    return json_encode([
        'service' => 'S3EC PHP v2 Test Server',
        'status' => 'running',
        'port' => 8087,
        'endpoints' => [
            'GET /' => 'Server status',
            'POST /client' => 'Create an S3EncryptionClient and cache it.',
            'GET /object/{bucket}/{key}' => 'Handle GET requests to /object/{bucket}/{key} by using the S3EncryptionClient to make a GetObject request to S3.',
            'PUT /object/{bucket}/{key}' => 'Handle PUT requests to /object/{bucket}/{key} by using the S3EncryptionClient to make a PutObject request to S3.',
        ]
    ]);
});

$router->addRoute('GET', '/cache', function () {
    return json_encode([
        'sessionId' => session_id(),
        'sessionStatus' => session_status(),
        'totalCachedClients' => count($_SESSION['s3ecCache'] ?? []),
        'allClientIds' => array_keys($_SESSION['s3ecCache'] ?? []),
        'cacheDetails' => $_SESSION['s3ecCache'] ?? []
    ]);
});

$router->addRoute('GET', '/object/{bucket}/{key}', function ($params) {
    return handleGetObject($params);
});

$router->addRoute('PUT', '/object/{bucket}/{key}', function ($params) {
    return handlePutObject($params);
});

$router->addRoute('POST', '/client', function () {
    return handleCreateClient();
});

// Handle the request and output response
$result = $router->handleRequest();
if ($result !== false) {
    echo $result;
}
