# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Tests for key derivation specification compliance annotations.

Each test in this module corresponds to a MUST requirement from
specification/s3-encryption/key-derivation.md and carries a type=test annotation
that mirrors the type=implementation annotation in the source code.
"""

import hmac

import pytest
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.hashes import SHA512
from cryptography.hazmat.primitives.kdf.hkdf import HKDFExpand

from s3_encryption.key_derivation import (
    derive_keys,
)
from s3_encryption.materials.materials import AlgorithmSuite

_KC_SUITE = AlgorithmSuite.ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY
SUITE_ID_BYTES = _KC_SUITE.suite_id_bytes
ENCRYPTION_KEY_LENGTH = _KC_SUITE.data_key_length_bytes
COMMIT_KEY_LENGTH = _KC_SUITE.commitment_length_bytes
MESSAGE_ID_LENGTH = _KC_SUITE.commitment_nonce_length_bytes
KC_GCM_IV = _KC_SUITE.kc_gcm_iv


# ---------------------------------------------------------------------------
# HKDF Extract / Expand
# ---------------------------------------------------------------------------

class TestHkdfOperation:
    """Tests for specification/s3-encryption/key-derivation.md#hkdf-operation."""

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The hash function MUST be specified by the algorithm suite commitment settings.
    def test_hash_function_is_sha512(self):
        """HKDF extract MUST use HMAC-SHA512 as the hash function."""
        import os
        pdk = os.urandom(32)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)

        # Manual HMAC-SHA512 extract
        prk = hmac.new(msg_id, pdk, "sha512").digest()
        assert len(prk) == 64  # SHA-512 output

        # derive_keys should produce deterministic output consistent with SHA-512
        key1, ck1 = derive_keys(pdk, msg_id, _KC_SUITE)
        key2, ck2 = derive_keys(pdk, msg_id, _KC_SUITE)
        assert key1 == key2
        assert ck1 == ck2

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The input keying material MUST be the plaintext data key (PDK) generated by the key provider.
    def test_ikm_is_plaintext_data_key(self):
        """Different plaintext data keys MUST produce different derived keys."""
        import os
        msg_id = os.urandom(MESSAGE_ID_LENGTH)
        pdk_a = os.urandom(32)
        pdk_b = os.urandom(32)

        key_a, _ = derive_keys(pdk_a, msg_id, _KC_SUITE)
        key_b, _ = derive_keys(pdk_b, msg_id, _KC_SUITE)
        assert key_a != key_b

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The length of the input keying material MUST equal the key derivation input length specified by the algorithm suite commit key derivation setting.
    def test_ikm_length_is_32_bytes(self):
        """The plaintext data key (IKM) MUST be 32 bytes for AES-256."""
        import os
        pdk = os.urandom(32)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)
        assert len(pdk) == 32
        # Should succeed with 32-byte key
        key, ck = derive_keys(pdk, msg_id, _KC_SUITE)
        assert len(key) == ENCRYPTION_KEY_LENGTH
        assert len(ck) == COMMIT_KEY_LENGTH

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The salt MUST be the Message ID with the length defined in the algorithm suite.
    def test_salt_is_message_id(self):
        """Different Message IDs (salts) MUST produce different derived keys."""
        import os
        pdk = os.urandom(32)
        msg_id_a = os.urandom(MESSAGE_ID_LENGTH)
        msg_id_b = os.urandom(MESSAGE_ID_LENGTH)

        key_a, _ = derive_keys(pdk, msg_id_a, _KC_SUITE)
        key_b, _ = derive_keys(pdk, msg_id_b, _KC_SUITE)
        assert key_a != key_b

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The DEK input pseudorandom key MUST be the output from the extract step.
    def test_dek_uses_prk_from_extract(self):
        """The DEK expand step MUST use the PRK from the extract step."""
        import os
        pdk = os.urandom(32)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)

        # Manual extract
        prk = hmac.new(msg_id, pdk, "sha512").digest()
        # Manual expand for DEK
        expected_dek = HKDFExpand(
            algorithm=SHA512(), length=ENCRYPTION_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"DERIVEKEY",
        ).derive(prk)

        actual_dek, _ = derive_keys(pdk, msg_id, _KC_SUITE)
        assert actual_dek == expected_dek

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The length of the output keying material MUST equal the encryption key length specified by the algorithm suite encryption settings.
    def test_dek_output_length(self):
        """The derived encryption key MUST be 32 bytes (256 bits)."""
        import os
        key, _ = derive_keys(os.urandom(32), os.urandom(MESSAGE_ID_LENGTH), _KC_SUITE)
        assert len(key) == ENCRYPTION_KEY_LENGTH
        assert ENCRYPTION_KEY_LENGTH == 32

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The input info MUST be a concatenation of the algorithm suite ID as bytes followed by the string DERIVEKEY as UTF8 encoded bytes.
    def test_dek_info_is_suite_id_plus_derivekey(self):
        """DEK expand info MUST be suite_id_bytes + b'DERIVEKEY'."""
        import os
        pdk = os.urandom(32)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)

        prk = hmac.new(msg_id, pdk, "sha512").digest()

        # Correct info
        correct_dek = HKDFExpand(
            algorithm=SHA512(), length=ENCRYPTION_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"DERIVEKEY",
        ).derive(prk)

        # Wrong info should produce different output
        wrong_dek = HKDFExpand(
            algorithm=SHA512(), length=ENCRYPTION_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"WRONGKEY",
        ).derive(prk)

        actual_dek, _ = derive_keys(pdk, msg_id, _KC_SUITE)
        assert actual_dek == correct_dek
        assert actual_dek != wrong_dek

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The CK input pseudorandom key MUST be the output from the extract step.
    def test_ck_uses_prk_from_extract(self):
        """The CK expand step MUST use the PRK from the extract step."""
        import os
        pdk = os.urandom(32)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)

        prk = hmac.new(msg_id, pdk, "sha512").digest()
        expected_ck = HKDFExpand(
            algorithm=SHA512(), length=COMMIT_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"COMMITKEY",
        ).derive(prk)

        _, actual_ck = derive_keys(pdk, msg_id, _KC_SUITE)
        assert actual_ck == expected_ck

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The length of the output keying material MUST equal the commit key length specified by the supported algorithm suites.
    def test_ck_output_length(self):
        """The commit key MUST be 28 bytes (224 bits)."""
        import os
        _, ck = derive_keys(os.urandom(32), os.urandom(MESSAGE_ID_LENGTH), _KC_SUITE)
        assert len(ck) == COMMIT_KEY_LENGTH
        assert COMMIT_KEY_LENGTH == 28

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The input info MUST be a concatenation of the algorithm suite ID as bytes followed by the string COMMITKEY as UTF8 encoded bytes.
    def test_ck_info_is_suite_id_plus_commitkey(self):
        """CK expand info MUST be suite_id_bytes + b'COMMITKEY'."""
        import os
        pdk = os.urandom(32)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)

        prk = hmac.new(msg_id, pdk, "sha512").digest()

        correct_ck = HKDFExpand(
            algorithm=SHA512(), length=COMMIT_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"COMMITKEY",
        ).derive(prk)

        wrong_ck = HKDFExpand(
            algorithm=SHA512(), length=COMMIT_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"WRONGKEY",
        ).derive(prk)

        _, actual_ck = derive_keys(pdk, msg_id, _KC_SUITE)
        assert actual_ck == correct_ck
        assert actual_ck != wrong_ck


# ---------------------------------------------------------------------------
# IV and AAD for KC-GCM
# ---------------------------------------------------------------------------

class TestKcGcmCipherParams:
    """Tests for KC-GCM cipher initialization parameters."""

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% When encrypting or decrypting with ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY,
    ##% the IV used in the AES-GCM content encryption/decryption MUST consist entirely of bytes with the value 0x01.
    def test_kc_gcm_iv_is_all_0x01(self):
        """The KC-GCM IV MUST consist entirely of 0x01 bytes."""
        assert all(b == 0x01 for b in KC_GCM_IV)

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% The IV's total length MUST match the IV length defined by the algorithm suite.
    def test_kc_gcm_iv_length_is_12(self):
        """The KC-GCM IV MUST be 12 bytes (AES-GCM standard nonce length)."""
        assert len(KC_GCM_IV) == 12

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% The client MUST initialize the cipher, or call an AES-GCM encryption API, with the derived encryption key, an IV containing only bytes with the value 0x01,
    ##% and the tag length defined in the Algorithm Suite when encrypting or decrypting with ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% The client MUST set the AAD to the Algorithm Suite ID represented as bytes.
    def test_kc_gcm_roundtrip_with_derived_key_iv_aad(self):
        """KC-GCM MUST encrypt/decrypt with derived key, 0x01 IV, and suite ID as AAD."""
        import os
        pdk = os.urandom(32)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)
        plaintext = b"key derivation roundtrip test"

        derived_key, _ = derive_keys(pdk, msg_id, _KC_SUITE)

        # Encrypt with derived key, KC_GCM_IV, and SUITE_ID_BYTES as AAD
        aesgcm = AESGCM(derived_key)
        ciphertext = aesgcm.encrypt(KC_GCM_IV, plaintext, SUITE_ID_BYTES)

        # Decrypt with same parameters
        decrypted = aesgcm.decrypt(KC_GCM_IV, ciphertext, SUITE_ID_BYTES)
        assert decrypted == plaintext

        # Decrypting with wrong AAD must fail
        with pytest.raises(Exception):
            aesgcm.decrypt(KC_GCM_IV, ciphertext, b"\x00\x00")

        # Decrypting with wrong IV must fail
        with pytest.raises(Exception):
            aesgcm.decrypt(b"\x00" * 12, ciphertext, SUITE_ID_BYTES)
