# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Tests for key derivation specification compliance annotations.

Each test in this module corresponds to a MUST requirement from
specification/s3-encryption/key-derivation.md and carries a type=test annotation
that mirrors the type=implementation annotation in the source code.
"""

import hmac
import os

import pytest
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.hashes import SHA512
from cryptography.hazmat.primitives.kdf.hkdf import HKDFExpand

from s3_encryption.key_derivation import (
    derive_keys,
)
from s3_encryption.materials.materials import AlgorithmSuite

_KC_SUITE = AlgorithmSuite.ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY
SUITE_ID_BYTES = _KC_SUITE.suite_id_bytes
ENCRYPTION_KEY_LENGTH = _KC_SUITE.data_key_length_bytes
COMMIT_KEY_LENGTH = _KC_SUITE.commitment_length_bytes
MESSAGE_ID_LENGTH = _KC_SUITE.commitment_nonce_length_bytes
KC_GCM_IV = _KC_SUITE.kc_gcm_iv


# ---------------------------------------------------------------------------
# HKDF Extract / Expand
# ---------------------------------------------------------------------------


class TestHkdfOperation:
    """Tests for specification/s3-encryption/key-derivation.md#hkdf-operation."""

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The hash function MUST be specified by the algorithm suite commitment settings.
    def test_hash_function_is_sha512(self):
        """HKDF extract MUST use the hash function specified by the algorithm suite."""

        pdk = os.urandom(_KC_SUITE.data_key_length_bytes)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)

        # Manual extract using the algorithm suite's configured hash
        hash_alg = _KC_SUITE.kdf_hash_algorithm
        prk = hmac.new(msg_id, pdk, hash_alg).digest()

        # Expand with the same hash to get expected DEK
        expected_dek = HKDFExpand(
            algorithm=SHA512(),
            length=_KC_SUITE.data_key_length_bytes,
            info=SUITE_ID_BYTES + b"DERIVEKEY",
        ).derive(prk)

        # derive_keys using the suite must match
        actual_dek, _ = derive_keys(pdk, msg_id, _KC_SUITE)
        assert actual_dek == expected_dek

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The input keying material MUST be the plaintext data key (PDK) generated by the key provider.
    def test_ikm_is_plaintext_data_key(self):
        """Different plaintext data keys MUST produce different derived keys."""

        msg_id = os.urandom(MESSAGE_ID_LENGTH)
        pdk_a = os.urandom(_KC_SUITE.data_key_length_bytes)
        pdk_b = os.urandom(_KC_SUITE.data_key_length_bytes)

        key_a, _ = derive_keys(pdk_a, msg_id, _KC_SUITE)
        key_b, _ = derive_keys(pdk_b, msg_id, _KC_SUITE)
        assert key_a != key_b

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The length of the input keying material MUST equal the key derivation input length specified by the algorithm suite commit key derivation setting.
    def test_ikm_length_is_32_bytes(self):
        """The plaintext data key (IKM) length MUST equal the algorithm suite's data key length."""

        pdk = os.urandom(_KC_SUITE.data_key_length_bytes)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)
        assert len(pdk) == _KC_SUITE.data_key_length_bytes
        # Should succeed with correct-length key
        key, ck = derive_keys(pdk, msg_id, _KC_SUITE)
        assert len(key) == ENCRYPTION_KEY_LENGTH
        assert len(ck) == COMMIT_KEY_LENGTH

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The length of the input keying material MUST equal the key derivation input length specified by the algorithm suite commit key derivation setting.
    def test_ikm_wrong_length_raises(self):
        """derive_keys MUST raise when the plaintext data key length doesn't match the suite."""

        from s3_encryption.exceptions import S3EncryptionClientError

        msg_id = os.urandom(MESSAGE_ID_LENGTH)
        # Too short
        with pytest.raises(S3EncryptionClientError):
            derive_keys(os.urandom(16), msg_id, _KC_SUITE)
        # Too long
        with pytest.raises(S3EncryptionClientError):
            derive_keys(os.urandom(64), msg_id, _KC_SUITE)

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The salt MUST be the Message ID with the length defined in the algorithm suite.
    def test_salt_is_message_id(self):
        """Different Message IDs (salts) MUST produce different derived keys."""

        pdk = os.urandom(_KC_SUITE.data_key_length_bytes)
        msg_id_a = os.urandom(MESSAGE_ID_LENGTH)
        msg_id_b = os.urandom(MESSAGE_ID_LENGTH)

        key_a, _ = derive_keys(pdk, msg_id_a, _KC_SUITE)
        key_b, _ = derive_keys(pdk, msg_id_b, _KC_SUITE)
        assert key_a != key_b

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The DEK input pseudorandom key MUST be the output from the extract step.
    def test_dek_uses_prk_from_extract(self):
        """The DEK expand step MUST use the PRK from the extract step."""

        pdk = os.urandom(_KC_SUITE.data_key_length_bytes)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)

        # Manual extract
        prk = hmac.new(msg_id, pdk, _KC_SUITE.kdf_hash_algorithm).digest()
        # Manual expand for DEK
        expected_dek = HKDFExpand(
            algorithm=SHA512(),
            length=ENCRYPTION_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"DERIVEKEY",
        ).derive(prk)

        actual_dek, _ = derive_keys(pdk, msg_id, _KC_SUITE)
        assert actual_dek == expected_dek

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The length of the output keying material MUST equal the encryption key length specified by the algorithm suite encryption settings.
    def test_dek_output_length(self):
        """The derived encryption key MUST match the encryption key length from the algorithm suite."""

        key, _ = derive_keys(
            os.urandom(_KC_SUITE.data_key_length_bytes), os.urandom(MESSAGE_ID_LENGTH), _KC_SUITE
        )
        assert len(key) == _KC_SUITE.data_key_length_bytes

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The input info MUST be a concatenation of the algorithm suite ID as bytes followed by the string DERIVEKEY as UTF8 encoded bytes.
    def test_dek_info_is_suite_id_plus_derivekey(self):
        """DEK expand info MUST be suite_id_bytes + b'DERIVEKEY'."""

        pdk = os.urandom(_KC_SUITE.data_key_length_bytes)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)

        prk = hmac.new(msg_id, pdk, _KC_SUITE.kdf_hash_algorithm).digest()

        # Correct info
        correct_dek = HKDFExpand(
            algorithm=SHA512(),
            length=ENCRYPTION_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"DERIVEKEY",
        ).derive(prk)

        # Wrong info should produce different output
        wrong_dek = HKDFExpand(
            algorithm=SHA512(),
            length=ENCRYPTION_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"WRONGKEY",
        ).derive(prk)

        actual_dek, _ = derive_keys(pdk, msg_id, _KC_SUITE)
        assert actual_dek == correct_dek
        assert actual_dek != wrong_dek

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The CK input pseudorandom key MUST be the output from the extract step.
    def test_ck_uses_prk_from_extract(self):
        """The CK expand step MUST use the PRK from the extract step."""

        pdk = os.urandom(_KC_SUITE.data_key_length_bytes)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)

        prk = hmac.new(msg_id, pdk, _KC_SUITE.kdf_hash_algorithm).digest()
        expected_ck = HKDFExpand(
            algorithm=SHA512(),
            length=COMMIT_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"COMMITKEY",
        ).derive(prk)

        _, actual_ck = derive_keys(pdk, msg_id, _KC_SUITE)
        assert actual_ck == expected_ck

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The length of the output keying material MUST equal the commit key length specified by the supported algorithm suites.
    def test_ck_output_length(self):
        """The commit key length MUST match the algorithm suite's commitment length."""

        _, ck = derive_keys(
            os.urandom(_KC_SUITE.data_key_length_bytes), os.urandom(MESSAGE_ID_LENGTH), _KC_SUITE
        )
        assert len(ck) == _KC_SUITE.commitment_length_bytes

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% - The input info MUST be a concatenation of the algorithm suite ID as bytes followed by the string COMMITKEY as UTF8 encoded bytes.
    def test_ck_info_is_suite_id_plus_commitkey(self):
        """CK expand info MUST be suite_id_bytes + b'COMMITKEY'."""

        pdk = os.urandom(_KC_SUITE.data_key_length_bytes)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)

        prk = hmac.new(msg_id, pdk, _KC_SUITE.kdf_hash_algorithm).digest()

        correct_ck = HKDFExpand(
            algorithm=SHA512(),
            length=COMMIT_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"COMMITKEY",
        ).derive(prk)

        wrong_ck = HKDFExpand(
            algorithm=SHA512(),
            length=COMMIT_KEY_LENGTH,
            info=SUITE_ID_BYTES + b"WRONGKEY",
        ).derive(prk)

        _, actual_ck = derive_keys(pdk, msg_id, _KC_SUITE)
        assert actual_ck == correct_ck
        assert actual_ck != wrong_ck


# ---------------------------------------------------------------------------
# IV and AAD for KC-GCM
# ---------------------------------------------------------------------------


class TestKcGcmCipherParams:
    """Tests for KC-GCM cipher initialization parameters."""

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% When encrypting or decrypting with ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY,
    ##% the IV used in the AES-GCM content encryption/decryption MUST consist entirely of bytes with the value 0x01.
    def test_kc_gcm_iv_is_all_0x01(self):
        """The KC-GCM IV MUST consist entirely of 0x01 bytes."""
        assert all(b == 0x01 for b in KC_GCM_IV)

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% The IV's total length MUST match the IV length defined by the algorithm suite.
    def test_kc_gcm_iv_length_is_12(self):
        """The KC-GCM IV length MUST match the IV length defined by the algorithm suite."""
        assert len(KC_GCM_IV) == _KC_SUITE.cipher_iv_length_bytes

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% The client MUST initialize the cipher, or call an AES-GCM encryption API, with the derived encryption key, an IV containing only bytes with the value 0x01,
    ##% and the tag length defined in the Algorithm Suite when encrypting or decrypting with ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=test
    ##% The client MUST set the AAD to the Algorithm Suite ID represented as bytes.
    def test_kc_gcm_roundtrip_with_derived_key_iv_aad(self):
        """KC-GCM MUST encrypt/decrypt with derived key, 0x01 IV, and suite ID as AAD."""

        pdk = os.urandom(_KC_SUITE.data_key_length_bytes)
        msg_id = os.urandom(MESSAGE_ID_LENGTH)
        plaintext = b"key derivation roundtrip test"

        derived_key, _ = derive_keys(pdk, msg_id, _KC_SUITE)

        # Encrypt with derived key, KC_GCM_IV, and SUITE_ID_BYTES as AAD
        aesgcm = AESGCM(derived_key)
        ciphertext = aesgcm.encrypt(KC_GCM_IV, plaintext, SUITE_ID_BYTES)

        # Decrypt with same parameters
        decrypted = aesgcm.decrypt(KC_GCM_IV, ciphertext, SUITE_ID_BYTES)
        assert decrypted == plaintext

        # Decrypting with wrong AAD must fail
        with pytest.raises(Exception):
            aesgcm.decrypt(KC_GCM_IV, ciphertext, b"\x00\x00")

        # Decrypting with wrong IV must fail
        with pytest.raises(Exception):
            aesgcm.decrypt(b"\x00" * _KC_SUITE.cipher_iv_length_bytes, ciphertext, SUITE_ID_BYTES)
