source 'https://rubygems.org'

ruby '>= 2.7.0'

gem 'aws-sdk-s3', path: 'local-ruby-sdk/gems/aws-sdk-s3'
gem 'aws-sdk-kms', path: 'local-ruby-sdk/gems/aws-sdk-kms'
gem 'json', '~> 2.0'
gem 'rexml', '~> 3.0'

group :development do
  gem 'rubocop', '~> 1.0'
end
