target = "../specification/s3-encryption/data-format/metadata-strategy.md#instruction-file"

# Instruction File
#
# Instruction Files are a separate S3 object which contain content metadata.
# The S3EC MUST support writing some or all (depending on format) content metadata to an Instruction File.
# The content metadata stored in the Instruction File MUST be serialized to a JSON string.
# The serialized JSON string MUST be the only contents of the Instruction File.
# 
# Instruction File writes MUST NOT be enabled by default.
# Instruction File writes MUST be optionally configured during client creation or on each PutObject request.
# The default Instruction File behavior uses the same S3 object key as its associated object suffixed with ".instruction".
# 
# The S3EC MAY support re-encryption/key rotation via Instruction Files.
# Further details on Instruction File re-encryption can be found in (TODO).
# The S3EC MUST NOT support providing a custom Instruction File suffix on ordinary writes; custom suffixes MUST only be used during re-encryption.
# The S3EC SHOULD support providing a custom Instruction File suffix on GetObject requests, regardless of whether or not re-encryption is supported.

[[spec]]
level = "MUST"
quote = '''
The S3EC MUST support writing some or all (depending on format) content metadata to an Instruction File.
'''

[[spec]]
level = "MUST"
quote = '''
The content metadata stored in the Instruction File MUST be serialized to a JSON string.
'''

[[spec]]
level = "MUST"
quote = '''
The serialized JSON string MUST be the only contents of the Instruction File.
'''

[[spec]]
level = "MUST"
quote = '''
Instruction File writes MUST NOT be enabled by default.
'''

[[spec]]
level = "MUST"
quote = '''
Instruction File writes MUST be optionally configured during client creation or on each PutObject request.
'''

[[spec]]
level = "MAY"
quote = '''
The S3EC MAY support re-encryption/key rotation via Instruction Files.
'''

[[spec]]
level = "MUST"
quote = '''
The S3EC MUST NOT support providing a custom Instruction File suffix on ordinary writes; custom suffixes MUST only be used during re-encryption.
'''

[[spec]]
level = "SHOULD"
quote = '''
The S3EC SHOULD support providing a custom Instruction File suffix on GetObject requests, regardless of whether or not re-encryption is supported.
'''

