target = "../specification/s3-encryption/data-format/metadata-strategy.md#v3-instruction-files"

# V3 Instruction Files
#
# In the V3 message format, only the content metadata related to the encrypted data is stored in the Instruction File.
# In the V3 message format, the content metadata related to the encrypted content is stored in the Object Metadata.
# 
# - The V3 message format MUST store the mapkey "x-amz-c" and its value in the Object Metadata when writing with an Instruction File.
# - The V3 message format MUST NOT store the mapkey "x-amz-c" and its value in the Instruction File.
# - The V3 message format MUST store the mapkey "x-amz-d" and its value in the Object Metadata when writing with an Instruction File.
# - The V3 message format MUST NOT store the mapkey "x-amz-d" and its value in the Instruction File.
# - The V3 message format MUST store the mapkey "x-amz-i" and its value in the Object Metadata when writing with an Instruction File.
# - The V3 message format MUST NOT store the mapkey "x-amz-i" and its value in the Instruction File.
# 
# - The V3 message format MUST store the mapkey "x-amz-3" and its value in the Instruction File.
# - The V3 message format MUST store the mapkey "x-amz-w" and its value in the Instruction File.
# - The V3 message format MUST store the mapkey "x-amz-m" and its value (when present in the content metadata) in the Instruction File.
# - The V3 message format MUST store the mapkey "x-amz-t" and its value (when present in the content metadata) in the Instruction File.
# 
# This is done to facilitate data key re-encryption via Instruction File.

[[spec]]
level = "MUST"
quote = '''
- The V3 message format MUST store the mapkey "x-amz-c" and its value in the Object Metadata when writing with an Instruction File.
'''

[[spec]]
level = "MUST"
quote = '''
- The V3 message format MUST NOT store the mapkey "x-amz-c" and its value in the Instruction File.
'''

[[spec]]
level = "MUST"
quote = '''
- The V3 message format MUST store the mapkey "x-amz-d" and its value in the Object Metadata when writing with an Instruction File.
'''

[[spec]]
level = "MUST"
quote = '''
- The V3 message format MUST NOT store the mapkey "x-amz-d" and its value in the Instruction File.
'''

[[spec]]
level = "MUST"
quote = '''
- The V3 message format MUST store the mapkey "x-amz-i" and its value in the Object Metadata when writing with an Instruction File.
'''

[[spec]]
level = "MUST"
quote = '''
- The V3 message format MUST NOT store the mapkey "x-amz-i" and its value in the Instruction File.
'''

[[spec]]
level = "MUST"
quote = '''
- The V3 message format MUST store the mapkey "x-amz-3" and its value in the Instruction File.
'''

[[spec]]
level = "MUST"
quote = '''
- The V3 message format MUST store the mapkey "x-amz-w" and its value in the Instruction File.
'''

[[spec]]
level = "MUST"
quote = '''
- The V3 message format MUST store the mapkey "x-amz-m" and its value (when present in the content metadata) in the Instruction File.
'''

[[spec]]
level = "MUST"
quote = '''
- The V3 message format MUST store the mapkey "x-amz-t" and its value (when present in the content metadata) in the Instruction File.
'''

