target = "../specification/s3-encryption/decryption.md#decrypting-with-commitment"

# Decrypting With Commitment
#
# When using an algorithm suite which supports key commitment, the client MUST verify that the [derived key commitment](./key-derivation.md#hkdf-operation) contains the same bytes as the stored key commitment retrieved from the stored object's metadata.
# When using an algorithm suite which supports key commitment, the verification of the derived key commitment value MUST be done in constant time.
# When using an algorithm suite which supports key commitment, the client MUST throw an exception when the derived key commitment value and stored key commitment value do not match.
# When using an algorithm suite which supports key commitment, the client MUST verify the key commitment values match before deriving the [derived encryption key](./key-derivation.md#hkdf-operation).

[[spec]]
level = "MUST"
quote = '''
When using an algorithm suite which supports key commitment, the client MUST verify that the [derived key commitment](./key-derivation.md#hkdf-operation) contains the same bytes as the stored key commitment retrieved from the stored object's metadata.
'''

[[spec]]
level = "MUST"
quote = '''
When using an algorithm suite which supports key commitment, the verification of the derived key commitment value MUST be done in constant time.
'''

[[spec]]
level = "MUST"
quote = '''
When using an algorithm suite which supports key commitment, the client MUST throw an exception when the derived key commitment value and stored key commitment value do not match.
'''

[[spec]]
level = "MUST"
quote = '''
When using an algorithm suite which supports key commitment, the client MUST verify the key commitment values match before deriving the [derived encryption key](./key-derivation.md#hkdf-operation).
'''

