target = "../specification/s3-encryption/decryption.md#key-commitment"

# Key Commitment
#
# The S3EC supports algorithm suite(s) which provide [key commitment](./key-commitment.md).
# The S3EC MUST validate the algorithm suite used for decryption against the key commitment policy before attempting to decrypt the content ciphertext.
# If the commitment policy requires decryption using a committing algorithm suite, and the algorithm suite associated with the object does not support key commitment, then the S3EC MUST throw an exception.

[[spec]]
level = "MUST"
quote = '''
The S3EC MUST validate the algorithm suite used for decryption against the key commitment policy before attempting to decrypt the content ciphertext.
'''

[[spec]]
level = "MUST"
quote = '''
If the commitment policy requires decryption using a committing algorithm suite, and the algorithm suite associated with the object does not support key commitment, then the S3EC MUST throw an exception.
'''

