target = "../specification/s3-encryption/decryption.md#ranged-gets"

# Ranged Gets
#
# The S3EC MAY support the "range" parameter on GetObject which specifies a subset of bytes to download and decrypt.
# If the S3EC supports Ranged Gets, the S3EC MUST adjust the customer-provided range to include the beginning and end of the cipher blocks for the given range.
# TODO: Fully spec out all edge cases for Ranged Gets.
# For requests which provide a range to decrypt an object encrypted with an authenticated algorithm suite, the corresponding CTR-based algorithm suite is used.
# If the object was encrypted with ALG_AES_256_GCM_IV12_TAG16_NO_KDF, then ALG_AES_256_CTR_IV16_TAG16_NO_KDF MUST be used to decrypt the range of the object.
# If the object was encrypted with ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY, then ALG_AES_256_CTR_HKDF_SHA512_COMMIT_KEY MUST be used to decrypt the range of the object.
# 
# If the GetObject response contains a range, but the GetObject request does not contain a range, the S3EC MUST throw an exception.
# This behavior indicates that this is a "multipart download" which is currently not supported.

[[spec]]
level = "MAY"
quote = '''
The S3EC MAY support the "range" parameter on GetObject which specifies a subset of bytes to download and decrypt.
'''

[[spec]]
level = "MUST"
quote = '''
If the S3EC supports Ranged Gets, the S3EC MUST adjust the customer-provided range to include the beginning and end of the cipher blocks for the given range.
'''

[[spec]]
level = "MUST"
quote = '''
If the object was encrypted with ALG_AES_256_GCM_IV12_TAG16_NO_KDF, then ALG_AES_256_CTR_IV16_TAG16_NO_KDF MUST be used to decrypt the range of the object.
'''

[[spec]]
level = "MUST"
quote = '''
If the object was encrypted with ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY, then ALG_AES_256_CTR_HKDF_SHA512_COMMIT_KEY MUST be used to decrypt the range of the object.
'''

[[spec]]
level = "MUST"
quote = '''
If the GetObject response contains a range, but the GetObject request does not contain a range, the S3EC MUST throw an exception.
'''

