target = "../specification/s3-encryption/client.md#cryptographic-materials"

# Cryptographic Materials
#
# The S3EC MUST accept either one CMM or one Keyring instance upon initialization.
# If both a CMM and a Keyring are provided, the S3EC MUST throw an exception.
# When a Keyring is provided, the S3EC MUST create an instance of the DefaultCMM using the provided Keyring.
# 
# The S3EC MAY accept key material directly.
# When only key material is provided, a Keyring corresponding to the type of key material is created by default.
# This behavior is discouraged, as it requires all Keyring configuration options to be supported by client initialization.
# This leads to customer confusion when a Keyring is provided and a Keyring option is set on the client, and thus not applied.
# It is considered deprecated, meaning it will be removed in the next major version (v4).

[[spec]]
level = "MUST"
quote = '''
The S3EC MUST accept either one CMM or one Keyring instance upon initialization.
'''

[[spec]]
level = "MUST"
quote = '''
If both a CMM and a Keyring are provided, the S3EC MUST throw an exception.
'''

[[spec]]
level = "MUST"
quote = '''
When a Keyring is provided, the S3EC MUST create an instance of the DefaultCMM using the provided Keyring.
'''

[[spec]]
level = "MAY"
quote = '''
The S3EC MAY accept key material directly.
'''

