target = "../specification/s3-encryption/client.md#enable-delayed-authentication"

# Enable Delayed Authentication
#
# The S3EC MUST support the option to enable or disable Delayed Authentication mode.
# Delayed Authentication mode MUST be set to false by default.
# When enabled, the S3EC MAY release plaintext from a stream which has not been authenticated.
# When disabled the S3EC MUST NOT release plaintext from a stream which has not been authenticated.

[[spec]]
level = "MUST"
quote = '''
The S3EC MUST support the option to enable or disable Delayed Authentication mode.
'''

[[spec]]
level = "MUST"
quote = '''
Delayed Authentication mode MUST be set to false by default.
'''

[[spec]]
level = "MAY"
quote = '''
When enabled, the S3EC MAY release plaintext from a stream which has not been authenticated.
'''

[[spec]]
level = "MUST"
quote = '''
When disabled the S3EC MUST NOT release plaintext from a stream which has not been authenticated.
'''

