target = "../specification/s3-encryption/client.md#key-commitment"

# Key Commitment
#
# The S3EC MUST support configuration of the [Key Commitment policy](./key-commitment.md) during its initialization.
# The S3EC MUST validate the configured Encryption Algorithm against the provided key commitment policy.
# If the configured Encryption Algorithm is incompatible with the key commitment policy, then it MUST throw an exception.

[[spec]]
level = "MUST"
quote = '''
The S3EC MUST support configuration of the [Key Commitment policy](./key-commitment.md) during its initialization.
'''

[[spec]]
level = "MUST"
quote = '''
The S3EC MUST validate the configured Encryption Algorithm against the provided key commitment policy.
'''

[[spec]]
level = "MUST"
quote = '''
If the configured Encryption Algorithm is incompatible with the key commitment policy, then it MUST throw an exception.
'''

