target = "../specification/s3-encryption/client.md#optional-api-operations"

# Optional API Operations
#
# The S3EC may provide implementations for the following S3 operations:
# 
# - CreateMultipartUpload MAY be implemented by the S3EC.
#   - If implemented, CreateMultipartUpload MUST initiate a multipart upload.
# - UploadPart MAY be implemented by the S3EC.
#   - UploadPart MUST encrypt each part.
#   - Each part MUST be encrypted in sequence.
#   - Each part MUST be encrypted using the same cipher instance for each part.
# - CompleteMultipartUpload MAY be implemented by the S3EC.
#   - CompleteMultipartUpload MUST complete the multipart upload.
# - AbortMultipartUpload MAY be implemented by the S3EC.
#   - AbortMultipartUpload MUST abort the multipart upload.
# 
# The S3EC may provide implementations for the following S3EC-specific operation(s):
# 
# - ReEncryptInstructionFile MAY be implemented by the S3EC.
#   - ReEncryptInstructionFile MUST decrypt the instruction file's encrypted data key for the given object using the client's CMM.
#   - ReEncryptInstructionFile MUST re-encrypt the plaintext data key with a provided keyring.

[[spec]]
level = "MAY"
quote = '''
- CreateMultipartUpload MAY be implemented by the S3EC.
'''

[[spec]]
level = "MUST"
quote = '''
- If implemented, CreateMultipartUpload MUST initiate a multipart upload.
'''

[[spec]]
level = "MAY"
quote = '''
- UploadPart MAY be implemented by the S3EC.
'''

[[spec]]
level = "MUST"
quote = '''
- UploadPart MUST encrypt each part.
'''

[[spec]]
level = "MUST"
quote = '''
- Each part MUST be encrypted in sequence.
'''

[[spec]]
level = "MUST"
quote = '''
- Each part MUST be encrypted using the same cipher instance for each part.
'''

[[spec]]
level = "MAY"
quote = '''
- CompleteMultipartUpload MAY be implemented by the S3EC.
'''

[[spec]]
level = "MUST"
quote = '''
- CompleteMultipartUpload MUST complete the multipart upload.
'''

[[spec]]
level = "MAY"
quote = '''
- AbortMultipartUpload MAY be implemented by the S3EC.
'''

[[spec]]
level = "MUST"
quote = '''
- AbortMultipartUpload MUST abort the multipart upload.
'''

[[spec]]
level = "MAY"
quote = '''
- ReEncryptInstructionFile MAY be implemented by the S3EC.
'''

[[spec]]
level = "MUST"
quote = '''
- ReEncryptInstructionFile MUST decrypt the instruction file's encrypted data key for the given object using the client's CMM.
'''

[[spec]]
level = "MUST"
quote = '''
- ReEncryptInstructionFile MUST re-encrypt the plaintext data key with a provided keyring.
'''

