target = "../specification/s3-encryption/client.md#randomness"

# Randomness
#
# The S3EC MAY accept a source of randomness during client initialization.
# The inclusion of a source of randomness is subject to language availability.

[[spec]]
level = "MAY"
quote = '''
The S3EC MAY accept a source of randomness during client initialization.
'''

