target = "../specification/s3-encryption/client.md#required-api-operations"

# Required API Operations
#
# The S3EC must provide implementations for the following S3 operations:
# 
# - GetObject MUST be implemented by the S3EC.
#   - GetObject MUST decrypt data received from the S3 server and return it as plaintext.
# - PutObject MUST be implemented by the S3EC.
#   - PutObject MUST encrypt its input data before it is uploaded to S3.
# - DeleteObject MUST be implemented by the S3EC.
#   - DeleteObject MUST delete the given object key.
#   - DeleteObject MUST delete the associated instruction file using the default instruction file suffix.
# - DeleteObjects MUST be implemented by the S3EC.
#   - DeleteObjects MUST delete each of the given objects.
#   - DeleteObjects MUST delete each of the corresponding instruction files using the default instruction file suffix.

[[spec]]
level = "MUST"
quote = '''
- GetObject MUST be implemented by the S3EC.
'''

[[spec]]
level = "MUST"
quote = '''
- GetObject MUST decrypt data received from the S3 server and return it as plaintext.
'''

[[spec]]
level = "MUST"
quote = '''
- PutObject MUST be implemented by the S3EC.
'''

[[spec]]
level = "MUST"
quote = '''
- PutObject MUST encrypt its input data before it is uploaded to S3.
'''

[[spec]]
level = "MUST"
quote = '''
- DeleteObject MUST be implemented by the S3EC.
'''

[[spec]]
level = "MUST"
quote = '''
- DeleteObject MUST delete the given object key.
'''

[[spec]]
level = "MUST"
quote = '''
- DeleteObject MUST delete the associated instruction file using the default instruction file suffix.
'''

[[spec]]
level = "MUST"
quote = '''
- DeleteObjects MUST be implemented by the S3EC.
'''

[[spec]]
level = "MUST"
quote = '''
- DeleteObjects MUST delete each of the given objects.
'''

[[spec]]
level = "MUST"
quote = '''
- DeleteObjects MUST delete each of the corresponding instruction files using the default instruction file suffix.
'''

