'$schema' = "https://awslabs.github.io/duvet/config/v0.4.0.json"

[[source]]
pattern = "src/**/*.py"

[[source]]
pattern = "test/**/*.py"
type = "test"            # Sets the default annotation type

# Include required specifications here
# TODO only specs with exceptions are included at this time.
[[specification]]
source = "specification/s3-encryption/client.md"
[[specification]]
source = "specification/s3-encryption/data-format/content-metadata.md"
[[specification]]
source = "specification/s3-encryption/decryption.md"
[[specification]]
source = "specification/s3-encryption/materials/s3-keyring.md"

[report.html]
enabled = true
# Sets the path to the report output
path = ".duvet/reports/report.html"                     

# Enable snapshots to prevent requirement coverage regressions
[report.snapshot]
enabled = false