# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Key derivation for S3 Encryption Client key-committing algorithm suites.

Implements HKDF-based key derivation as specified in:
  specification/s3-encryption/key-derivation.md

For ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY:
  - Extract: HKDF-SHA512, salt = Message ID (28 bytes), IKM = plaintext data key
  - Expand (DEK): info = suite_id_bytes + b"DERIVEKEY", output = 32 bytes
  - Expand (Commit Key): info = suite_id_bytes + b"COMMITKEY", output = 28 bytes
"""

import hmac

from cryptography.hazmat.primitives.hashes import SHA512
from cryptography.hazmat.primitives.kdf.hkdf import HKDFExpand

from .exceptions import S3EncryptionClientSecurityError

# Algorithm suite ID for S3EC.ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY
SUITE_ID_BYTES = b"\x00\x73"

# Output lengths
ENCRYPTION_KEY_LENGTH = 32  # 256 bits
COMMIT_KEY_LENGTH = 28  # 224 bits
MESSAGE_ID_LENGTH = 28  # 224 bits (used as HKDF salt)

# Fixed IV for KC GCM: 12 bytes of 0x01
KC_GCM_IV = b"\x01" * 12


def _hkdf_extract(salt: bytes, ikm: bytes) -> bytes:
    """HKDF extract step using HMAC-SHA512.

    Args:
        salt: The salt value (Message ID).
        ikm: Input keying material (plaintext data key).

    Returns:
        The pseudorandom key (PRK).
    """
    return hmac.new(salt, ikm, "sha512").digest()


def _hkdf_expand(prk: bytes, info: bytes, length: int) -> bytes:
    """HKDF expand step using SHA-512.

    Args:
        prk: Pseudorandom key from extract step.
        info: Context/application-specific info string.
        length: Desired output length in bytes.

    Returns:
        Output keying material of the requested length.
    """
    hkdf = HKDFExpand(algorithm=SHA512(), length=length, info=info)
    return hkdf.derive(prk)


def derive_keys(plaintext_data_key: bytes, message_id: bytes) -> tuple[bytes, bytes]:
    """Derive the encryption key and commitment key from a plaintext data key.

    Uses HKDF with SHA-512 as specified in the S3EC key derivation spec.

    Args:
        plaintext_data_key: The plaintext data key from the keyring (32 bytes).
        message_id: The generated Message ID used as the HKDF salt (28 bytes).

    Returns:
        A tuple of (derived_encryption_key, commit_key).
    """
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The hash function MUST be specified by the algorithm suite commitment settings.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The input keying material MUST be the plaintext data key (PDK) generated by the key provider.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The length of the input keying material MUST equal the key derivation input length specified by the algorithm suite commit key derivation setting.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The salt MUST be the Message ID with the length defined in the algorithm suite.
    prk = _hkdf_extract(salt=message_id, ikm=plaintext_data_key)

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The DEK input pseudorandom key MUST be the output from the extract step.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The length of the output keying material MUST equal the encryption key length specified by the algorithm suite encryption settings.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The input info MUST be a concatenation of the algorithm suite ID as bytes
    ##% followed by the string DERIVEKEY as UTF8 encoded bytes.
    derived_encryption_key = _hkdf_expand(
        prk, info=SUITE_ID_BYTES + b"DERIVEKEY", length=ENCRYPTION_KEY_LENGTH
    )

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The CK input pseudorandom key MUST be the output from the extract step.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The length of the output keying material MUST equal the commit key length specified by the supported algorithm suites.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The input info MUST be a concatenation of the algorithm suite ID as bytes
    ##% followed by the string COMMITKEY as UTF8 encoded bytes.
    commit_key = _hkdf_expand(prk, info=SUITE_ID_BYTES + b"COMMITKEY", length=COMMIT_KEY_LENGTH)

    return derived_encryption_key, commit_key


def verify_commitment(stored_commitment: bytes, derived_commitment: bytes) -> None:
    """Verify key commitment in constant time.

    Args:
        stored_commitment: The commitment value from the object metadata.
        derived_commitment: The commitment value derived from the data key.

    Raises:
        S3EncryptionClientSecurityError: If the commitment values do not match.
    """
    ##= specification/s3-encryption/decryption.md#decrypting-with-commitment
    ##= type=implementation
    ##% When using an algorithm suite which supports key commitment, the verification of the derived key commitment value MUST be done in constant time.
    ##= specification/s3-encryption/decryption.md#decrypting-with-commitment
    ##= type=implementation
    ##% When using an algorithm suite which supports key commitment, the client MUST throw an exception when the derived key commitment value
    ##% and stored key commitment value do not match.
    if not hmac.compare_digest(stored_commitment, derived_commitment):
        raise S3EncryptionClientSecurityError(
            "Key commitment verification failed: stored commitment does not match derived commitment."
        )
