# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Key derivation for S3 Encryption Client key-committing algorithm suites.

Implements HKDF-based key derivation as specified in:
  specification/s3-encryption/key-derivation.md

For ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY:
  - Extract: HKDF-SHA512, salt = Message ID (28 bytes), IKM = plaintext data key
  - Expand (DEK): info = suite_id_bytes + b"DERIVEKEY", output = 32 bytes
  - Expand (Commit Key): info = suite_id_bytes + b"COMMITKEY", output = 28 bytes
"""

from __future__ import annotations

import hmac
from typing import TYPE_CHECKING

from cryptography.hazmat.primitives.hashes import SHA512
from cryptography.hazmat.primitives.kdf.hkdf import HKDFExpand

from .exceptions import S3EncryptionClientError, S3EncryptionClientSecurityError

if TYPE_CHECKING:
    from .materials.materials import AlgorithmSuite

# Map of supported KDF hash algorithm names to cryptography hash classes.
_HASH_ALGORITHMS = {
    "sha512": SHA512,
}


def _hkdf_extract(salt: bytes, ikm: bytes, hash_algorithm: str) -> bytes:
    """HKDF extract step using HMAC.

    Args:
        salt: The salt value (Message ID).
        ikm: Input keying material (plaintext data key).
        hash_algorithm: Hash algorithm name (e.g. "sha512").

    Returns:
        The pseudorandom key (PRK).
    """
    return hmac.new(salt, ikm, hash_algorithm).digest()


def _hkdf_expand(prk: bytes, info: bytes, length: int, hash_algorithm: str) -> bytes:
    """HKDF expand step.

    Args:
        prk: Pseudorandom key from extract step.
        info: Context/application-specific info string.
        length: Desired output length in bytes.
        hash_algorithm: Hash algorithm name (e.g. "sha512").

    Returns:
        Output keying material of the requested length.

    Raises:
        S3EncryptionClientError: If the hash algorithm is not supported.
    """
    hash_cls = _HASH_ALGORITHMS.get(hash_algorithm)
    if hash_cls is None:
        raise S3EncryptionClientError(
            f"Unsupported KDF hash algorithm: {hash_algorithm}"
        )
    hkdf = HKDFExpand(algorithm=hash_cls(), length=length, info=info)
    return hkdf.derive(prk)


def derive_keys(
    plaintext_data_key: bytes,
    message_id: bytes,
    algorithm_suite: AlgorithmSuite,
) -> tuple[bytes, bytes]:
    """Derive the encryption key and commitment key from a plaintext data key.

    Uses HKDF with SHA-512 as specified in the S3EC key derivation spec.

    Args:
        plaintext_data_key: The plaintext data key from the keyring.
        message_id: The generated Message ID used as the HKDF salt.
        algorithm_suite: The algorithm suite whose parameters drive key lengths
            and info strings.

    Returns:
        A tuple of (derived_encryption_key, commit_key).
    """
    suite_id = algorithm_suite.suite_id_bytes
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The length of the output keying material MUST equal the encryption key length specified by the algorithm suite encryption settings.
    enc_key_len = algorithm_suite.data_key_length_bytes
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The length of the output keying material MUST equal the commit key length specified by the supported algorithm suites.
    commit_key_len = algorithm_suite.commitment_length_bytes
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The hash function MUST be specified by the algorithm suite commitment settings.
    hash_alg = algorithm_suite.kdf_hash_algorithm

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The length of the input keying material MUST equal the key derivation input length specified by the algorithm suite commit key derivation setting.
    if len(plaintext_data_key) != enc_key_len:
        raise S3EncryptionClientError(
            f"Plaintext data key length ({len(plaintext_data_key)}) does not match "
            f"the key derivation input length ({enc_key_len}) specified by the algorithm suite."
        )

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The input keying material MUST be the plaintext data key (PDK) generated by the key provider.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The salt MUST be the Message ID with the length defined in the algorithm suite.
    prk = _hkdf_extract(salt=message_id, ikm=plaintext_data_key, hash_algorithm=hash_alg)

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The DEK input pseudorandom key MUST be the output from the extract step.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The input info MUST be a concatenation of the algorithm suite ID as bytes
    ##% followed by the string DERIVEKEY as UTF8 encoded bytes.
    derived_encryption_key = _hkdf_expand(
        prk, info=suite_id + b"DERIVEKEY", length=enc_key_len, hash_algorithm=hash_alg
    )

    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The CK input pseudorandom key MUST be the output from the extract step.
    ##= specification/s3-encryption/key-derivation.md#hkdf-operation
    ##= type=implementation
    ##% - The input info MUST be a concatenation of the algorithm suite ID as bytes
    ##% followed by the string COMMITKEY as UTF8 encoded bytes.
    commit_key = _hkdf_expand(prk, info=suite_id + b"COMMITKEY", length=commit_key_len, hash_algorithm=hash_alg)

    return derived_encryption_key, commit_key


def verify_commitment(stored_commitment: bytes, derived_commitment: bytes) -> None:
    """Verify key commitment in constant time.

    Args:
        stored_commitment: The commitment value from the object metadata.
        derived_commitment: The commitment value derived from the data key.

    Raises:
        S3EncryptionClientSecurityError: If the commitment values do not match.
    """
    ##= specification/s3-encryption/decryption.md#decrypting-with-commitment
    ##= type=implementation
    ##% When using an algorithm suite which supports key commitment, the verification of the derived key commitment value MUST be done in constant time.
    ##= specification/s3-encryption/decryption.md#decrypting-with-commitment
    ##= type=implementation
    ##% When using an algorithm suite which supports key commitment, the client MUST throw an exception when the derived key commitment value
    ##% and stored key commitment value do not match.
    if not hmac.compare_digest(stored_commitment, derived_commitment):
        raise S3EncryptionClientSecurityError(
            "Key commitment verification failed: stored commitment does not match derived commitment."
        )
