target = "../specification/s3-encryption/encryption.md#alg-aes-256-ctr-iv16-tag16-no-kdf"

# ALG_AES_256_CTR_IV16_TAG16_NO_KDF
#
# Encryption using AES-CTR is not supported.
# This algorithm suite is only used to decrypt ranges of a ciphertext encrypted using AES-GCM.
# Attempts to encrypt using AES-CTR MUST fail.

[[spec]]
level = "MUST"
quote = '''
Attempts to encrypt using AES-CTR MUST fail.
'''

