target = "../specification/s3-encryption/encryption.md#cipher-initialization"

# Cipher Initialization
#
# The client SHOULD validate that the generated IV or Message ID is not zeros.
# There is an astoundingly small chance that an IV or Message ID is generated as all zeros.
# An IV or Message ID containing all zeros is valid, but it is more likely that the IV/Message ID was not initialized or generated correctly.
# 
# The rest of the cipher initialization depends on the algorithm suite:

[[spec]]
level = "SHOULD"
quote = '''
The client SHOULD validate that the generated IV or Message ID is not zeros.
'''

