target = "../specification/s3-encryption/data-format/content-metadata.md#v1-v2-shared"

# V1/V2 Shared
#
# The following mapkeys are used in both the V1 and V2 format.
# 
# _x-amz-matdesc_
# 
# A JSON string containing the Material Description OR Encryption Context used when encrypting the data key.
# See TODO-link for more details on Material Description and Encryption Context.
# This string MAY be encoded by the esoteric double-encoding scheme used by the S3 web server.
# See TODO-link for more details on the S3 double-encoding scheme.
# The default value is the an empty JSON map (`{}`).
# 
# _x-amz-iv_
# 
# The base64-encoded bytes used as the IV when encrypting the content.

[[spec]]
level = "MAY"
quote = '''
This string MAY be encoded by the esoteric double-encoding scheme used by the S3 web server.
'''

