name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use'
        default: '3.11'
        required: false
        type: string

jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ inputs.python-version || '3.11' }}
    secrets: inherit
    env:
      CI_KMS_KEY_ALIAS: ${{ vars.CI_KMS_KEY_ALIAS }}
      CI_S3_BUCKET: ${{ vars.CI_S3_BUCKET }}
