name: Main Workflow

on:
  push:
    branches: [ main, fireegg-test-servers ]
  pull_request:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use'
        default: '3.11'
        required: false
        type: string

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  run-tests:
    permissions:
      id-token: write
      contents: read
    name: Run Tests
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ inputs.python-version || '3.11' }}
    secrets: inherit

  run-duvet:
    permissions:
      id-token: write
      contents: read
      pages: write
    name: Run Duvet
    uses: ./.github/workflows/duvet.yml
    secrets: inherit
