name: Python Integration Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        default: "3.11"
        required: false
        type: string

jobs:
  python-integ:
    runs-on: macos-14-large
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version || '3.11' }}
      
      - name: Cache uv dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('./test-server/python-v3-server/**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install Uv
        run: pip install uv

      - name: Install dependencies
        run: make install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::370957321024:role/S3EC-Python-Github-test-role
          aws-region: us-west-2

      - name: Run unit tests
        run: make test-unit

      - name: Run integration tests
        run: make test-integration
        env:
          CI_S3_BUCKET: ${{ vars.CI_S3_BUCKET }}
          CI_KMS_KEY_ALIAS: ${{ vars.CI_KMS_KEY_ALIAS }}

      - name: Generate coverage HTML report
        if: always()
        run: uv run coverage html -d coverage-report

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: coverage-report/
